#pragma once

// Macros for cluster IDs
// TODO: this is not a complete list
#define MATTER_IDENTIFY_CLUSTER_ID                              0x0003
#define MATTER_GROUPS_CLUSTER_ID                                0x0004
#define MATTER_SCENES_CLUSTER_ID                                0x0005
#define MATTER_ONOFF_CLUSTER_ID                                 0x0006
#define MATTER_ONOFF_SWITCH_CONFIGURATION_CLUSTER_ID            0x0007
#define MATTER_LEVELCONTROL_CLUSTER_ID                          0x0008

// Macros for attribute IDs
// TODO: this is not a complete list

// Onoff cluster attributes
#define MATTER_ONOFF_ONOFF_ATTRIBUTE_ID                         0x0000
#define MATTER_ONOFF_GLOBALSCENECONTROL_ATTRIBUTE_ID            0x4000
#define MATTER_ONOFF_ONTIME_ATTRIBUTE_ID                        0x4001
#define MATTER_ONOFF_OFFWAITTIME_ATTRIBUTE_ID                   0x4002
#define MATTER_ONOFF_STARTUPONOFF_ATTRIBUTE_ID                  0x4003

// Levelcontrol cluster attributes
#define MATTER_LEVELCONTROL_CURRENTLEVEL_ATTRIBUTE_ID           0x0000
#define MATTER_LEVELCONTROL_REMAININGTIME_ATTRIBUTE_ID          0x0001
#define MATTER_LEVELCONTROL_MINLEVEL_ATTRIBUTE_ID               0x0002
#define MATTER_LEVELCONTROL_MAXLEVEL_ATTRIBUTE_ID               0x0003
#define MATTER_LEVELCONTROL_CURRENTFREQUENCY_ATTRIBUTE_ID       0x0004
#define MATTER_LEVELCONTROL_MINFREQUENCY_ATTRIBUTE_ID           0x0005
#define MATTER_LEVELCONTROL_MAXFREQUENCY_ATTRIBUTE_ID           0x0006
#define MATTER_LEVELCONTROL_OPTIONS_ATTRIBUTE_ID                0x000F
#define MATTER_LEVELCONTROL_ONOFFTRANSITIONTIME_ATTRIBUTE_ID    0x0010
#define MATTER_LEVELCONTROL_ONLEVEL_ATTRIBUTE_ID                0x0011
#define MATTER_LEVELCONTROL_ONTRANSITIONTIME_ATTRIBUTE_ID       0x0012
#define MATTER_LEVELCONTROL_OFFTRANSITIONTIME_ATTRIBUTE_ID      0x0013
#define MATTER_LEVELCONTROL_DEFAULTMOVERATE_ATTRIBUTE_ID        0x0014
#define MATTER_LEVELCONTROL_STARTUPCURRENTLEVEL_ATTRIBUTE_ID    0x4000
