#pragma once

// Macros for cluster IDs
// TODO: this is not a complete list
#define MATTER_IDENTIFY_CLUSTER_ID                              0x0003
#define MATTER_GROUPS_CLUSTER_ID                                0x0004
#define MATTER_SCENES_CLUSTER_ID                                0x0005
#define MATTER_ONOFF_CLUSTER_ID                                 0x0006
#define MATTER_ONOFF_SWITCH_CONFIGURATION_CLUSTER_ID            0x0007
#define MATTER_LEVELCONTROL_CLUSTER_ID                          0x0008
#define MATTER_COLORCONTROL_CLUSTER_ID                          0x0300

// Macros for attribute IDs
// TODO: this is not a complete list

// Onoff cluster attributes
#define MATTER_ONOFF_ONOFF_ATTRIBUTE_ID                         0x0000
#define MATTER_ONOFF_GLOBALSCENECONTROL_ATTRIBUTE_ID            0x4000
#define MATTER_ONOFF_ONTIME_ATTRIBUTE_ID                        0x4001
#define MATTER_ONOFF_OFFWAITTIME_ATTRIBUTE_ID                   0x4002
#define MATTER_ONOFF_STARTUPONOFF_ATTRIBUTE_ID                  0x4003

// Levelcontrol cluster attributes
#define MATTER_LEVELCONTROL_CURRENTLEVEL_ATTRIBUTE_ID           0x0000
#define MATTER_LEVELCONTROL_REMAININGTIME_ATTRIBUTE_ID          0x0001
#define MATTER_LEVELCONTROL_MINLEVEL_ATTRIBUTE_ID               0x0002
#define MATTER_LEVELCONTROL_MAXLEVEL_ATTRIBUTE_ID               0x0003
#define MATTER_LEVELCONTROL_CURRENTFREQUENCY_ATTRIBUTE_ID       0x0004
#define MATTER_LEVELCONTROL_MINFREQUENCY_ATTRIBUTE_ID           0x0005
#define MATTER_LEVELCONTROL_MAXFREQUENCY_ATTRIBUTE_ID           0x0006
#define MATTER_LEVELCONTROL_OPTIONS_ATTRIBUTE_ID                0x000F
#define MATTER_LEVELCONTROL_ONOFFTRANSITIONTIME_ATTRIBUTE_ID    0x0010
#define MATTER_LEVELCONTROL_ONLEVEL_ATTRIBUTE_ID                0x0011
#define MATTER_LEVELCONTROL_ONTRANSITIONTIME_ATTRIBUTE_ID       0x0012
#define MATTER_LEVELCONTROL_OFFTRANSITIONTIME_ATTRIBUTE_ID      0x0013
#define MATTER_LEVELCONTROL_DEFAULTMOVERATE_ATTRIBUTE_ID        0x0014
#define MATTER_LEVELCONTROL_STARTUPCURRENTLEVEL_ATTRIBUTE_ID    0x4000

// Colorcontrol cluster attributes
#define MATTER_COLORCONTROL_CURRENTHUE_ATTRIBUTE_ID                                     0x0000
#define MATTER_COLORCONTROL_CURRENTSATURATION_ATTRIBUTE_ID                              0x0001
#define MATTER_COLORCONTROL_REMAININGTIME_ATTRIBUTE_ID                                  0x0002
#define MATTER_COLORCONTROL_CURRENTX_ATTRIBUTE_ID                                       0x0003
#define MATTER_COLORCONTROL_CURRENTY_ATTRIBUTE_ID                                       0x0004
#define MATTER_COLORCONTROL_DRIFTCOMPENSATION_ATTRIBUTE_ID                              0x0005
#define MATTER_COLORCONTROL_COMPENSATIONTEXT_ATTRIBUTE_ID                               0x0006
#define MATTER_COLORCONTROL_COLORTEMPERATUREMIREDS_ATTRIBUTE_ID                         0x0007
#define MATTER_COLORCONTROL_COLORMODE_ATTRIBUTE_ID                                      0x0008
#define MATTER_COLORCONTROL_OPTIONS_ATTRIBUTE_ID                                        0x000F
#define MATTER_COLORCONTROL_NUMBEROFPRIMARIES_ATTRIBUTE_ID                              0x0010
#define MATTER_COLORCONTROL_PRIMARY1X_ATTRIBUTE_ID                                      0x0011
#define MATTER_COLORCONTROL_PRIMARY1Y_ATTRIBUTE_ID                                      0x0012
#define MATTER_COLORCONTROL_PRIMARY1INTENSITY_ATTRIBUTE_ID                              0x0013
#define MATTER_COLORCONTROL_PRIMARY2X_ATTRIBUTE_ID                                      0x0015
#define MATTER_COLORCONTROL_PRIMARY2Y_ATTRIBUTE_ID                                      0x0016
#define MATTER_COLORCONTROL_PRIMARY2INTENSITY_ATTRIBUTE_ID                              0x0017
#define MATTER_COLORCONTROL_PRIMARY3X_ATTRIBUTE_ID                                      0x0019
#define MATTER_COLORCONTROL_PRIMARY3Y_ATTRIBUTE_ID                                      0x001A
#define MATTER_COLORCONTROL_PRIMARY3INTENSITY_ATTRIBUTE_ID                              0x001B
#define MATTER_COLORCONTROL_PRIMARY4X_ATTRIBUTE_ID                                      0x0020
#define MATTER_COLORCONTROL_PRIMARY4Y_ATTRIBUTE_ID                                      0x0021
#define MATTER_COLORCONTROL_PRIMARY4INTENSITY_ATTRIBUTE_ID                              0x0022
#define MATTER_COLORCONTROL_PRIMARY5X_ATTRIBUTE_ID                                      0x0024
#define MATTER_COLORCONTROL_PRIMARY5Y_ATTRIBUTE_ID                                      0x0025
#define MATTER_COLORCONTROL_PRIMARY5INTENSITY_ATTRIBUTE_ID                              0x0026
#define MATTER_COLORCONTROL_PRIMARY6X_ATTRIBUTE_ID                                      0x0028
#define MATTER_COLORCONTROL_PRIMARY6Y_ATTRIBUTE_ID                                      0x0029
#define MATTER_COLORCONTROL_PRIMARY6INTENSITY_ATTRIBUTE_ID                              0x002A
#define MATTER_COLORCONTROL_WHITEPOINTX_ATTRIBUTE_ID                                    0x0030
#define MATTER_COLORCONTROL_WHITEPOINTY_ATTRIBUTE_ID                                    0x0031
#define MATTER_COLORCONTROL_COLORPOINTRX_ATTRIBUTE_ID                                   0x0032
#define MATTER_COLORCONTROL_COLORPOINTRY_ATTRIBUTE_ID                                   0x0033
#define MATTER_COLORCONTROL_COLORPOINTRINTENSITY_ATTRIBUTE_ID                           0x0034
#define MATTER_COLORCONTROL_COLORPOINTGX_ATTRIBUTE_ID                                   0x0036
#define MATTER_COLORCONTROL_COLORPOINTGY_ATTRIBUTE_ID                                   0x0037
#define MATTER_COLORCONTROL_COLORPOINTGINTENSITY_ATTRIBUTE_ID                           0x0038
#define MATTER_COLORCONTROL_COLORPOINTBX_ATTRIBUTE_ID                                   0x003A
#define MATTER_COLORCONTROL_COLORPOINTBY_ATTRIBUTE_ID                                   0x003B
#define MATTER_COLORCONTROL_COLORPOINTBINTENSITY_ATTRIBUTE_ID                           0x003C
#define MATTER_COLORCONTROL_ENHANCEDCURRENTHUE_ATTRIBUTE_ID                             0x4000
#define MATTER_COLORCONTROL_ENHANCEDCURRENTMODE_ATTRIBUTE_ID                            0x4001
#define MATTER_COLORCONTROL_COLORLOOPACTIVE_ATTRIBUTE_ID                                0x4002
#define MATTER_COLORCONTROL_COLORLOOPDIRECTION_ATTRIBUTE_ID                             0x4003
#define MATTER_COLORCONTROL_COLORLOOPTIME_ATTRIBUTE_ID                                  0x4004
#define MATTER_COLORCONTROL_COLORLOOPSTARTENHANCEDHUE_ATTRIBUTE_ID                      0x4005
#define MATTER_COLORCONTROL_COLORLOOPSTOREDENHANCEDHUE_ATTRIBUTE_ID                     0x4006
#define MATTER_COLORCONTROL_COLORCAPABILITIES_ATTRIBUTE_ID                              0x400A
#define MATTER_COLORCONTROL_COLORTEMPPHYSICALMINMIREDS_ATTRIBUTE_ID                     0x400B
#define MATTER_COLORCONTROL_COLORTEMPPHYSICALMAXMIREDS_ATTRIBUTE_ID                     0x400C
#define MATTER_COLORCONTROL_COUPLECOLORTEMPTOLEVELMINMIREDS_ATTRIBUTE_ID                0x400D
#define MATTER_COLORCONTROL_STARTUPCOLORTEMPERATUREMIREDS_ATTRIBUTE_ID                  0x4010

