# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ameba_factory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61meba_factory.proto\"+\n\nBytesField\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\x0e\n\x06length\x18\x02 \x01(\x05\"\xa0\x01\n\x1a\x43ommissionableDataProvider\x12\x10\n\x08passcode\x18\x01 \x01(\x05\x12\x15\n\rdiscriminator\x18\x02 \x01(\x05\x12\x11\n\tspake2_it\x18\x03 \x01(\x05\x12 \n\x0bspake2_salt\x18\x04 \x01(\x0b\x32\x0b.BytesField\x12$\n\x0fspake2_verifier\x18\x05 \x01(\x0b\x32\x0b.BytesField\"\x9b\x01\n$DeviceAttestationCredentialsProvider\x12\x1d\n\x08\x64\x61\x63_cert\x18\x01 \x01(\x0b\x32\x0b.BytesField\x12\x1c\n\x07\x64\x61\x63_key\x18\x02 \x01(\x0b\x32\x0b.BytesField\x12\x1d\n\x08pai_cert\x18\x03 \x01(\x0b\x32\x0b.BytesField\x12\x17\n\x02\x63\x64\x18\x04 \x01(\x0b\x32\x0b.BytesField\"\x9c\x02\n\x1a\x44\x65viceInstanceInfoProvider\x12\x11\n\tvendor_id\x18\x01 \x01(\x05\x12 \n\x0bvendor_name\x18\x02 \x01(\x0b\x32\x0b.BytesField\x12\x12\n\nproduct_id\x18\x03 \x01(\x05\x12!\n\x0cproduct_name\x18\x04 \x01(\x0b\x32\x0b.BytesField\x12\x0e\n\x06hw_ver\x18\x05 \x01(\x05\x12\"\n\rhw_ver_string\x18\x06 \x01(\x0b\x32\x0b.BytesField\x12\x1d\n\x08mfg_date\x18\x07 \x01(\x0b\x32\x0b.BytesField\x12\x1f\n\nserial_num\x18\x08 \x01(\x0b\x32\x0b.BytesField\x12\x1e\n\trd_id_uid\x18\t \x01(\x0b\x32\x0b.BytesField\"\x9f\x01\n\x13\x46\x61\x63toryDataProvider\x12*\n\x05\x63\x64\x61ta\x18\x01 \x01(\x0b\x32\x1b.CommissionableDataProvider\x12\x32\n\x03\x64\x61\x63\x18\x02 \x01(\x0b\x32%.DeviceAttestationCredentialsProvider\x12(\n\x03\x64ii\x18\x03 \x01(\x0b\x32\x1b.DeviceInstanceInfoProviderb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ameba_factory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BYTESFIELD._serialized_start=23
  _BYTESFIELD._serialized_end=66
  _COMMISSIONABLEDATAPROVIDER._serialized_start=69
  _COMMISSIONABLEDATAPROVIDER._serialized_end=229
  _DEVICEATTESTATIONCREDENTIALSPROVIDER._serialized_start=232
  _DEVICEATTESTATIONCREDENTIALSPROVIDER._serialized_end=387
  _DEVICEINSTANCEINFOPROVIDER._serialized_start=390
  _DEVICEINSTANCEINFOPROVIDER._serialized_end=674
  _FACTORYDATAPROVIDER._serialized_start=677
  _FACTORYDATAPROVIDER._serialized_end=836
# @@protoc_insertion_point(module_scope)
