/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "ameba_factory.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(BytesField, BytesField, AUTO)


PB_BIND(CommissionableDataProvider, CommissionableDataProvider, AUTO)


PB_BIND(DeviceAttestationCredentialsProvider, DeviceAttestationCredentialsProvider, AUTO)


PB_BIND(DeviceInstanceInfoProvider, DeviceInstanceInfoProvider, AUTO)


PB_BIND(FactoryDataProvider, FactoryDataProvider, 2)



